services:
  backend-dev:
    container_name: backend-dev
    build:
      context: .
      dockerfile: backend/Dockerfile.development
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 4000M
    ports:
      - "3000:3000" # HOST_PORT:CONTAINER_PORT
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      NODE_OPTIONS: "--max-old-space-size=4096"
      POSTGRES_HOST: db
    env_file:
      - ./.env.development
      - ./.env
    depends_on:
      - db

  app-dev:
    container_name: app-dev
    build:
      context: .
      dockerfile: frontend/Dockerfile.development
    restart: unless-stopped
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - ./.env.development
      - ./.env
    depends_on:
      - backend-dev

  backend-prod:
    container_name: backend-prod
    build:
      context: .
      dockerfile: backend/Dockerfile.production
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 4000M
    ports:
      - "8080:8080"
    environment:
      NODE_OPTIONS: "--max-old-space-size=4096"
      POSTGRES_HOST: db
    env_file:
      - ./.env.production
      - ./.env
    depends_on:
      - db

  app-prod:
    container_name: app-prod
    build:
      context: .
      dockerfile: frontend/Dockerfile.production
      args:
        - VITE_API_URL=http://localhost:8080/api
        - VITE_GOOGLE_CLIENT_ID=${VITE_GOOGLE_CLIENT_ID}
        - VITE_UNSPLASH_API_KEY=${VITE_UNSPLASH_API_KEY}
    restart: unless-stopped
    ports:
      - "8000:80"
    env_file:
      - ./.env.production
      - ./.env
    depends_on:
      - backend-prod

  db:
    container_name: db
    image: postgres:latest
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql

volumes:
  pgdata: {}
