# development stage
FROM node:lts-alpine AS dev

WORKDIR /app

COPY backend/package*.json ./
RUN npm install

COPY backend/ .

ENV NODE_OPTIONS="--max-old-space-size=4096"

CMD ["npm", "run", "start:dev"]

# build stage
FROM node:lts-alpine AS build

WORKDIR /app

COPY backend/package*.json ./
RUN npm install

COPY backend/ .

ENV NODE_OPTIONS="--max-old-space-size=4096"

RUN npm run build

# production stage
FROM node:lts-alpine AS prod

WORKDIR /app

COPY --from=build /app/dist ./dist
COPY --from=build /app/node_modules ./node_modules
COPY backend/package*.json ./

CMD ["npm", "run", "start:prod"]
