export const shortcuts = [
  { sc: 'Ctrl+Z', explanation: 'Undo' },
  { sc: 'Ctrl+Y', explanation: 'Redo' },
  { sc: 'Ctrl+Shift+Z', explanation: 'Redo' },
  { sc: 'Ctrl+C', explanation: 'Copy selected objects' },
  { sc: 'Ctrl+X', explanation: 'Cut selected objects' },
  { sc: 'Ctrl+V', explanation: 'Paste copied objects' },
  { sc: 'Ctrl+S', explanation: 'Save project' },
  { sc: 'Ctrl+O', explanation: 'Add image from computer' },
  { sc: 'Ctrl++', explanation: 'Zoom in' },
  { sc: 'Ctrl+-', explanation: 'Zoom out' },
  { sc: 'Ctrl+0', explanation: 'Reset zoom' },
  { sc: 'Ctrl+[', explanation: 'Move selected layer backward' },
  { sc: 'Ctrl+]', explanation: 'Move selected layer forward' },
  { sc: '← ↑ ↓ →', explanation: 'Move selected objects by 1 px' },
  { sc: 'Shift+↑', explanation: 'Move selected objects by 10 px' },
  { sc: 'Del / Bksp', explanation: 'Delete selected objects' },
  { sc: 'Ctrl+A', explanation: 'Select all objects' },
  { sc: 'Esc', explanation: 'Clear selection' },
];
